name: New Issue Notifier

on:
  issues:
    types: [opened]

jobs:
  notify-neoxr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const issue = context.payload.issue
            const message = `
            Hi @${issue.user.login} ðŸ‘‹

            We appreciate your report: **${issue.title}**  
            This report has been forwarded to the owner via WhatsApp and will be reviewed soon.

            > [!NOTE]
            > Check the issues in the [Baileys repository](https://github.com/WhiskeySockets/Baileys/issues) first to verify whether the problem originates from this script or from the Baileys module.
            `
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: message
            })

      - name: Send issue info to owner via WhatsApp
        run: |
          curl -X POST "https://bot.neoxr.eu/v1/text" \
            --header "x-neoxr-token: ${{ secrets.WG_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data-raw "{
              \"number\": \"${{ secrets.WG_NUMBER }}\",
              \"text\": \"ðŸ”” Issue baru dari repository *${{ github.repository }}*:\\n\\n#${{ github.event.issue.number }} - ${{ github.event.issue.title }}\\n\\n${{ github.event.issue.html_url }}\"
            }"
